name: Dependabot auto-merge
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot auto-merge
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          target: minor
